name: Workflow Demo

on: 
  push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Echo ACCESS_ID
      run: echo "${{ vars.ACCESS_ID1 }}"    
    - name: Echo Secrets
      run: echo "${{ secrets.ACCESS_ID }}"


